
// This file is automatically generated by the Firebase setup tool.
import { FirebaseOptions, initializeApp } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyBckbnkKF7I_uqEZEgwvdYQ968F-pItmmE",
  authDomain: "gem-tracker-b71hl.firebaseapp.com",
  databaseURL: "https://gem-tracker-b71hl-default-rtdb.firebaseio.com",
  projectId: "gem-tracker-b71hl",
  storageBucket: "gem-tracker-b71hl.appspot.com",
  messagingSenderId: "607236477290",
  appId: "1:607236477290:web:939188363a59434aef1513"
};

export const app = initializeApp(firebaseConfig);

    